server:
  port: 8001
spring:
  application:
    name: ent-cache
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  redis:
    database: 0
    pool:
      max-active: 100 #连接池最大连接数（负值表示没有限制）
      max-wait: 3000 #连接池最大阻塞等待时间（负值表示没有限制）
      max-idle: 200 #连接池最大空闭连接数
      min-idle: 50 #连接汉最小空闲连接数
      timeout: 600 #连接超时时间（毫秒）
    password: 123456
    sentinel:
      master: mymaster
      nodes:
        - 192.168.67.201:5000
        - 192.168.67.202:5000
        - 192.168.67.203:5000
  kafka:
    bootstrap-servers: 192.168.67.201:9092,192.168.67.202:9092,192.168.67.203:9092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual
    topic: ent_rebuild_cache
  zookeeper:
    url: 192.168.67.201:2181,192.168.67.202:2181,192.168.67.203:2181
    timeout: 1000
    retry: 3
  cache:
    cache-name: ent-cache
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
management:
  endpoints:
    web:
      exposure:
        include: *