server:
  port: 8003
spring:
  dataSource:
    url: jdbc:mysql://localhost:3306/ent?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  redis:
    database: 0
    pool:
      max-active: 100 #连接池最大连接数（负值表示没有限制）
      max-wait: 3000 #连接池最大阻塞等待时间（负值表示没有限制）
      max-idle: 200 #连接池最大空闭连接数
      min-idle: 50 #连接汉最小空闲连接数
      timeout: 600 #连接超时时间（毫秒）
    password: 123456
    sentinel:
      master: mymaster
      nodes:
        - 192.168.67.201:5000
        - 192.168.67.202:5000
        - 192.168.67.203:5000
#    cluster:
#      nodes:
#        - 192.168.67.201:5000
#        - 192.168.67.202:5000
#        - 192.168.67.203:5000